// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users(id, email, password)
VALUES($1, $2, $3)
RETURNING id, created_at, updated_at, email, password, is_chirpy_red
`

type CreateUserParams struct {
	ID       uuid.UUID
	Email    string
	Password string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser, arg.ID, arg.Email, arg.Password)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Email,
		&i.Password,
		&i.IsChirpyRed,
	)
	return i, err
}

const deleteAllUsers = `-- name: DeleteAllUsers :exec
DELETE FROM users
`

func (q *Queries) DeleteAllUsers(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteAllUsers)
	return err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, created_at, updated_at, email, password, is_chirpy_red FROM users WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Email,
		&i.Password,
		&i.IsChirpyRed,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, created_at, updated_at, email, password, is_chirpy_red FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Email,
		&i.Password,
		&i.IsChirpyRed,
	)
	return i, err
}

const updateChirpyIsRed = `-- name: UpdateChirpyIsRed :exec
UPDATE users
SET is_chirpy_red = TRUE, updated_at = $1
WHERE id = $2
`

type UpdateChirpyIsRedParams struct {
	UpdatedAt time.Time
	ID        uuid.UUID
}

func (q *Queries) UpdateChirpyIsRed(ctx context.Context, arg UpdateChirpyIsRedParams) error {
	_, err := q.db.ExecContext(ctx, updateChirpyIsRed, arg.UpdatedAt, arg.ID)
	return err
}

const updateUserByEmailAndPassword = `-- name: UpdateUserByEmailAndPassword :exec
UPDATE users
SET email = $1, password = $2
WHERE id = $3
`

type UpdateUserByEmailAndPasswordParams struct {
	Email    string
	Password string
	ID       uuid.UUID
}

func (q *Queries) UpdateUserByEmailAndPassword(ctx context.Context, arg UpdateUserByEmailAndPasswordParams) error {
	_, err := q.db.ExecContext(ctx, updateUserByEmailAndPassword, arg.Email, arg.Password, arg.ID)
	return err
}
